version: 0.2

phases:
    install:
      commands:
          - npm install
    build:
        commands:
            - echo Installing Composer Dependencies on `date`
            - mkdir ./var
            - composer install -o --no-progress --no-suggest
artifacts:
    files:
        - '**/*'